name: Check
on:
  pull_request: ~
  push:
    branches:
    - main

permissions: read-all

jobs:
  codeql:
    name: CodeQL (actions)
    runs-on: ubuntu-24.04
    permissions:
      security-events: write # To upload CodeQL results
    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - name: Initialize CodeQL
      uses: github/codeql-action/init@45775bd8235c68ba998cffa5171334d58593da47 # v3.28.15
      with:
        config-file: ./.github/codeql.yml
        languages: actions
    - name: Perform CodeQL analysis
      uses: github/codeql-action/analyze@45775bd8235c68ba998cffa5171334d58593da47 # v3.28.15
  dev-env:
    name: Dev env
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - name: Build development image
      run: make dev-img
  format:
    name: Format
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - name: Install tooling
      uses: asdf-vm/actions/install@1902764435ca0dd2f3388eea723a4f92a4eb8302 # v4.0.0
    - name: Check formatting
      run: make format-check
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - name: Install tooling
      uses: asdf-vm/actions/install@1902764435ca0dd2f3388eea723a4f92a4eb8302 # v4.0.0
    - name: Lint CI workflows
      if: ${{ failure() || success() }}
      run: make lint-ci
    - name: Lint Containerfile
      if: ${{ failure() || success() }}
      run: make lint-container
    - name: Lint shell scripts
      if: ${{ failure() || success() }}
      run: make lint-sh
  semgrep:
    name: Semgrep
    runs-on: ubuntu-24.04
    permissions:
      security-events: write # To upload SARIF results
    container:
      image: semgrep/semgrep
    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - name: Perform Semgrep analysis
      run: semgrep --sarif --output semgrep.sarif
    - name: Upload Semgrep report to GitHub
      uses: github/codeql-action/upload-sarif@45775bd8235c68ba998cffa5171334d58593da47 # v3.28.15
      if: ${{ failure() || success() }}
      with:
        sarif_file: semgrep.sarif
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - name: Test download
      run: make test-download version=0.1.6
    - name: Test install
      run: make test-install version=0.1.6
    - name: Test latest stable
      run: make test-latest-stable
    - name: Test list all
      run: make test-list-all
  test-e2e:
    name: Test end-to-end (${{ matrix.name }})
    runs-on: ${{ matrix.os }}
    needs:
    - test
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: MacOS
          os: macos-15
        - name: Ubuntu
          os: ubuntu-24.04
    steps:
    - name: asdf plugin test
      uses: asdf-vm/actions/plugin-test@1902764435ca0dd2f3388eea723a4f92a4eb8302 # v4.0.0
      with:
        command: diffoci --help
        version: 0.1.6
