name: Publish
on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+

permissions: read-all

jobs:
  github:
    name: GitHub Release
    runs-on: ubuntu-24.04
    permissions:
      contents: write # To create a GitHub Release
    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - name: Get version
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      id: version
      with:
        result-encoding: string
        script: |
          const ref = context.ref
          const tag = ref.replace(/^refs\/tags\//, "")
          return tag
    - name: Create GitHub Release
      uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 # v1.16.0
      with:
        name: Release ${{ steps.version.outputs.result }}
        body: Release ${{ steps.version.outputs.result }}
        tag: ${{ steps.version.outputs.result }}
        draft: false
        makeLatest: true
        prerelease: false
